/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppPage: typeof import('./src/components/app-page/app-page.vue')['default']
    AppTabbar: typeof import('./src/components/app-tabbar/app-tabbar.vue')['default']
    UAvatar: typeof import('uview-pro/components/u-avatar/u-avatar.vue')['default']
    UBadge: typeof import('uview-pro/components/u-badge/u-badge.vue')['default']
    UButton: typeof import('uview-pro/components/u-button/u-button.vue')['default']
    UCard: typeof import('uview-pro/components/u-card/u-card.vue')['default']
    UCellGroup: typeof import('uview-pro/components/u-cell-group/u-cell-group.vue')['default']
    UCellItem: typeof import('uview-pro/components/u-cell-item/u-cell-item.vue')['default']
    UCheckbox: typeof import('uview-pro/components/u-checkbox/u-checkbox.vue')['default']
    UCheckboxGroup: typeof import('uview-pro/components/u-checkbox-group/u-checkbox-group.vue')['default']
    UCollapse: typeof import('uview-pro/components/u-collapse/u-collapse.vue')['default']
    UCollapseItem: typeof import('uview-pro/components/u-collapse-item/u-collapse-item.vue')['default']
    UConfigProvider: typeof import('uview-pro/components/u-config-provider/u-config-provider.vue')['default']
    UGap: typeof import('uview-pro/components/u-gap/u-gap.vue')['default']
    UIcon: typeof import('uview-pro/components/u-icon/u-icon.vue')['default']
    UImage: typeof import('uview-pro/components/u-image/u-image.vue')['default']
    UInput: typeof import('uview-pro/components/u-input/u-input.vue')['default']
    ULink: typeof import('uview-pro/components/u-link/u-link.vue')['default']
    ULoading: typeof import('uview-pro/components/u-loading/u-loading.vue')['default']
    ULoadingPopup: typeof import('uview-pro/components/u-loading-popup/u-loading-popup.vue')['default']
    UMask: typeof import('uview-pro/components/u-mask/u-mask.vue')['default']
    UModal: typeof import('uview-pro/components/u-modal/u-modal.vue')['default']
    UNavbar: typeof import('uview-pro/components/u-navbar/u-navbar.vue')['default']
    UPopup: typeof import('uview-pro/components/u-popup/u-popup.vue')['default']
    URadio: typeof import('uview-pro/components/u-radio/u-radio.vue')['default']
    URadioGroup: typeof import('uview-pro/components/u-radio-group/u-radio-group.vue')['default']
    USlider: typeof import('uview-pro/components/u-slider/u-slider.vue')['default']
    USwitch: typeof import('uview-pro/components/u-switch/u-switch.vue')['default']
    UTabbar: typeof import('uview-pro/components/u-tabbar/u-tabbar.vue')['default']
    UTabs: typeof import('uview-pro/components/u-tabs/u-tabs.vue')['default']
    UTag: typeof import('uview-pro/components/u-tag/u-tag.vue')['default']
    UText: typeof import('uview-pro/components/u-text/u-text.vue')['default']
    UToast: typeof import('uview-pro/components/u-toast/u-toast.vue')['default']
    UTransition: typeof import('uview-pro/components/u-transition/u-transition.vue')['default']
  }
}
